sudo: true
language: ruby

before_script:
    - .travis/install-postgres.sh

script:
    - ruby extconf.rb --vendor --with-safe-level=1
    - make
    - sudo make install
    - make test

matrix:
  include:
    - env:
        - PG_VERSION=10
